version: "3"

services:

  jobmanager-te:
    build: .
    ports:
      - "8081:8081"
    command: >
        /opt/flink/bin/standalone-job.sh start-foreground
        --job-classname=org.sunbird.dp.extractor.task.TelemetryExtractorStreamTask
        -Djobmanager.rpc.address=jobmanager-te
        -Djobmanager.rpc.port=6123
        -Dparallelism.default=1
        -Dblob.server.port=6124
        -Dqueryable-state.server.ports=6125
        -Djobmanager.memory.process.size=256m
        -Djobmanager.memory.flink.size=192mb
        -Djobmanager.memory.heap.size=32m
        -Djobmanager.memory.off-heap.size=160m
        -Djobmanager.memory.jvm-metaspace.size=32mb
        -Djobmanager.memory.jvm-overhead.min=16m
        -Djobmanager.memory.jvm-overhead.max=32m
        -Djobmanager.memory.jvm-overhead.fraction=0.1
        --config.file.path /config/telemetry-extractor-comb.conf

  taskmanager-te:
    build: .
    depends_on:
      - jobmanager-te
    command: >
        /opt/flink/bin/taskmanager.sh start-foreground
        -Djobmanager.rpc.address=jobmanager-te
        -Dtaskmanager.rpc.port=6122
        -Dtaskmanager.memory.process.size=460m
        -Dtaskmanager.memory.flink.size=396mb
        -Dtaskmanager.memory.heap.size=128m
        -Dtaskmanager.memory.off-heap.size=128m
        -Dtaskmanager.memory.jvm-metaspace.size=32mb
        -Dtaskmanager.memory.jvm-overhead.min=16m
        -Dtaskmanager.memory.jvm-overhead.max=32m
        -Dtaskmanager.memory.jvm-overhead.fraction=0.1
    scale: 1
