version: "3"

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2182:2182"

  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_CREATE_TOPICS: "local.telemetry.ingest:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  jobmanager-te:
    build: .
    ports:
      - "8081:8081"
    command: >
        /opt/flink/bin/standalone-job.sh start-foreground
        --job-classname=org.sunbird.dp.extractor.task.TelemetryExtractorStreamTask
        -Djobmanager.rpc.address=jobmanager-te
        -Djobmanager.rpc.port=6123
        -Dparallelism.default=1
        -Dblob.server.port=6124
        -Dqueryable-state.server.ports=6125
        --config.file.path /config/telemetry-extractor-comb.conf

  taskmanager-te:
    build: .
    depends_on:
      - jobmanager-te
    command: >
        /opt/flink/bin/taskmanager.sh start-foreground
        -Djobmanager.rpc.address=jobmanager-te
        -Dtaskmanager.rpc.port=6122
    scale: 1
