version: "3"

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - target: 9094
        published: 9094
        protocol: tcp
        mode: host
    environment:
      HOSTNAME_COMMAND: "docker info | grep ^Name: | cut -d' ' -f 2"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INSIDE://:9092,OUTSIDE://_{HOSTNAME_COMMAND}:9094
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      AFKA_CREATE_TOPICS: "local.telemetry.ingest:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  jobmanager-te:
    build: .
    ports:
      - "8081:8081"
    command: >
        /opt/flink/bin/standalone-job.sh start-foreground
        --job-classname=org.sunbird.dp.extractor.task.TelemetryExtractorStreamTask
        -Djobmanager.rpc.address=jobmanager-te
        -Djobmanager.rpc.port=6123
        -Dparallelism.default=1
        -Dblob.server.port=6124
        -Dqueryable-state.server.ports=6125
        --config.file.path /config/telemetry-extractor-comb.conf

  taskmanager-te:
    build: .
    depends_on:
      - jobmanager-te
    command: >
        /opt/flink/bin/taskmanager.sh start-foreground
        -Djobmanager.rpc.address=jobmanager-te
        -Dtaskmanager.rpc.port=6122
    scale: 1
