version: "3"

services:
  jobmanager-te:
    build: .
    ports:
      - "8081:8081"
    command: >
        /opt/flink/bin/standalone-job.sh start-foreground
        --job-classname=org.sunbird.dp.extractor.task.TelemetryExtractorStreamTask
        -Djobmanager.rpc.address=jobmanager-te
        -Djobmanager.rpc.port=6123
        -Dparallelism.default=1
        -Dblob.server.port=6124
        -Dqueryable-state.server.ports=6125
        -Dconfig.file=/conf/telemetry-extractor-comb.conf

  taskmanager-te:
    build: .
    depends_on:
      - jobmanager-te
    command: >
        /opt/flink/bin/taskmanager.sh start-foreground
        -Djobmanager.rpc.address=jobmanager-te
        -Dtaskmanager.rpc.port=6122
        -Dconfig.file=/conf/telemetry-extractor-comb.conf
    scale: 1
